# Enable Firefox Remote Debugging Settings Automatically
# This script modifies Firefox's user.js file to enable remote debugging

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Firefox Remote Debugging Auto-Enable" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if Firefox is running
$firefoxProcess = Get-Process -Name "firefox" -ErrorAction SilentlyContinue
if ($firefoxProcess) {
    Write-Host "ERROR: Firefox is currently running!" -ForegroundColor Red
    Write-Host "Please close ALL Firefox windows and run this script again." -ForegroundColor Yellow
    Write-Host ""
    Read-Host -Prompt "Press Enter to exit"
    exit 1
}

Write-Host "Looking for Firefox profile..." -ForegroundColor Yellow

# Find Firefox profile directory
$firefoxProfilePath = "$env:APPDATA\Mozilla\Firefox\Profiles"

if (-not (Test-Path $firefoxProfilePath)) {
    Write-Host "ERROR: Firefox profile directory not found!" -ForegroundColor Red
    Write-Host "Expected location: $firefoxProfilePath" -ForegroundColor Yellow
    Write-Host ""
    Read-Host -Prompt "Press Enter to exit"
    exit 1
}

# Find the default profile (usually ends with .default-release)
$profiles = Get-ChildItem $firefoxProfilePath -Directory | Where-Object { $_.Name -like "*.default*" }

if ($profiles.Count -eq 0) {
    Write-Host "ERROR: No Firefox profile found!" -ForegroundColor Red
    Write-Host "Please run Firefox at least once to create a profile." -ForegroundColor Yellow
    Write-Host ""
    Read-Host -Prompt "Press Enter to exit"
    exit 1
}

# Use the first profile found (or default-release if available)
$defaultProfile = $profiles | Where-Object { $_.Name -like "*.default-release" } | Select-Object -First 1
if (-not $defaultProfile) {
    $defaultProfile = $profiles | Select-Object -First 1
}

$profilePath = $defaultProfile.FullName
Write-Host "Found profile: $($defaultProfile.Name)" -ForegroundColor Green
Write-Host "Path: $profilePath" -ForegroundColor Gray
Write-Host ""

# Create or update user.js file
$userJsPath = Join-Path $profilePath "user.js"

Write-Host "Configuring remote debugging settings..." -ForegroundColor Yellow

# Settings to enable
$settings = @"
// P-Texting Firefox Remote Debugging Settings
// Auto-generated by enable_firefox_debugging.ps1

// Enable remote debugging
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.chrome.enabled", true);

// Additional helpful settings for automation
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.debugger.force-local", false);

"@

# Write settings to user.js
try {
    Set-Content -Path $userJsPath -Value $settings -Force
    Write-Host "✓ Settings written to user.js" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Could not write to user.js file!" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host ""
    Read-Host -Prompt "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "SUCCESS! Firefox is now configured!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "1. Run: start_firefox_debug.bat" -ForegroundColor White
Write-Host "2. In Firefox, go to: https://voice.google.com/messages" -ForegroundColor White
Write-Host "3. Log in to Google Voice" -ForegroundColor White
Write-Host "4. In P-Texting GUI, select Firefox and click Send Messages" -ForegroundColor White
Write-Host ""
Write-Host "The settings will take effect when you start Firefox." -ForegroundColor Yellow
Write-Host ""
Read-Host -Prompt "Press Enter to exit"
